"""
Django settings for memory_viewer project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback is public (it's in this repo) and only fit for development.
# Production sets DJANGO_SECRET_KEY: it signs login challenges and cookies.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or 'django-insecure-zqun#rs1hda@a#za&#&9p7qs-5@hvh97nepfddp%mt6#^l078d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# Base allowed hosts
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.hunter.cryptograss.live', 'memory-lane', '5.78.83.4', 'justin-arthel', '172.18.0.2']

# Add any additional hosts from environment
extra_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
if extra_hosts:
    ALLOWED_HOSTS.extend(host.strip() for host in extra_hosts.split(',') if host.strip())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'conversations',
]

MIDDLEWARE = [
    # First, so every response is compressed: a Mood's first page is ~200 KB
    # of JSON uncompressed. (Django's GZip pads against BREACH.)
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'memory_viewer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'memory_viewer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Shared by every gunicorn worker in the container (unlike the default
# per-process memory cache): who is typing, sign-in rate limits.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.getenv('MEMORY_LANE_CACHE_DIR', '/tmp/memory-lane-cache'),
    }
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'magenta_memory'),
        'USER': os.getenv('POSTGRES_USER', 'magent'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'changeme'),
        'HOST': os.getenv('POSTGRES_HOST', 'magenta-postgres'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        # For async MCP server: don't persist connections (avoids stale connection errors)
        'CONN_MAX_AGE': 0,
        'CONN_HEALTH_CHECKS': True,
    }
}

# The watcher posts transcript lines in batches, and one line can hold a
# base64 screenshot (1 MB+). Django's 2.5 MB default refused such batches
# with a 400 the watcher then retried forever. The app's only POST
# endpoints are /api/ingest/ (key required) and the admin.
DATA_UPLOAD_MAX_MEMORY_SIZE = 32 * 1024 * 1024


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration - output to stderr so docker logs captures it
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',  # Log all request errors (500s, etc)
            'propagate': False,
        },
        'conversations': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# How much of a tool's output the record keeps, in characters. 0 keeps none:
# only which call it answered and whether it failed. Tool output holds file
# contents and command output -- a `cat .env` is a tool result -- the
# scrubber only removes secrets it already knows, and the read endpoints are
# public. Raise this deliberately.
TOOL_RESULT_CONTENT_CHARS = int(os.getenv('TOOL_RESULT_CONTENT_CHARS', '0'))

# Runners (poller/motion_poller.py) that stream agent turns into Motions:
# "agent:key,agent2:key2", each key from the vault. Unset, nobody can.
MOTION_RUNNER_KEYS = dict(
    pair.split(':', 1) for pair in os.getenv('MOTION_RUNNER_KEYS', '').split(',') if ':' in pair)

# The deploy scripts on maybelle (maybelle-config's report-deploy.sh) tell the
# Moods when a server is being redeployed, with this key from the vault
# (memory_lane_deploy_key). Unset, nobody can.
MOTION_DEPLOY_KEY = os.getenv('MOTION_DEPLOY_KEY', '')
# Voice (conversations/services/voice.py): ElevenLabs, for voice memos
# (speech to text) and reading messages aloud. Unset: no voice, and the
# page offers none.
ELEVENLABS_API_KEY = os.getenv('ELEVENLABS_API_KEY', '')
# Signing in with PickiPedia (conversations/services/wiki_auth.py): the
# client registered at the wiki's Special:OAuthConsumerRegistration. Unset:
# no wiki sign-in, only SSH keys.
PICKIPEDIA_OAUTH_CLIENT_ID = os.getenv('PICKIPEDIA_OAUTH_CLIENT_ID', '')
PICKIPEDIA_OAUTH_CLIENT_SECRET = os.getenv('PICKIPEDIA_OAUTH_CLIENT_SECRET', '')
# Each person's PickiPedia name, from hunter's inventory: "<name> <WikiName>" lines.
MOTION_WIKI_NAMES = os.getenv('MOTION_WIKI_NAMES', '')

# Who may kick, ban, scram (AZ5) and lift, with their SSH key
# (conversations/views_admin.py): "justin,skyler". Unset, nobody can.
MOTION_ADMINS = tuple(n.strip().lower() for n in os.getenv('MOTION_ADMINS', '').split(',') if n.strip())

# Hosts a Motion may embed images from by URL, besides its own stored media.
MOTION_IMAGE_HOSTS = {'pickipedia.xyz', 'www.pickipedia.xyz', 'raw.githubusercontent.com',
                      'user-images.githubusercontent.com', 'private-user-images.githubusercontent.com'}

# Writing into Motions (conversations/services/motion_auth.py): an OpenSSH
# allowed_signers file listing each person's key, generated at deploy from
# hunter's inventory. Unset or missing, nobody can enroll a device.
MOTION_ALLOWED_SIGNERS = os.getenv('MOTION_ALLOWED_SIGNERS', '')

# Behind Caddy, which terminates TLS and always sets X-Forwarded-Proto, so
# Django knows the request was https and a POST's Origin matches its own
# host. CSRF_TRUSTED_ORIGINS is only for *other* origins allowed to post
# here: exact hosts, never a wildcard -- every preview on hunter is a
# *.hunter.cryptograss.live origin, and none of them should post here.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS
                        if '.' in h and not h.startswith('.') and not h[0].isdigit()]

# Served only over https outside development.
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 365 * 24 * 3600  # this host only, no subdomains
