# Generated by Django 5.2.7 on 2026-09-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_motion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionSession',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_sessions', to='conversations.motion')),
            ],
            options={
                'db_table': 'motion_sessions',
                'ordering': ['claimed_at'],
            },
        ),
    ]
