# Generated by Django 5.2.7 on 2026-09-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_motionsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAnchor',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(db_index=True, help_text='Unix seconds')),
            ],
            options={
                'db_table': 'block_anchors',
                'ordering': ['number'],
            },
        ),
    ]
