# Generated by Django 5.2.7 on 2026-10-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mime', models.CharField(max_length=40)),
                ('data', models.BinaryField()),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='conversations.thinkingentity')),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
