# Generated by Django 5.2.7 on 2026-10-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='effort',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
