# Generated by Django 5.2.7 on 2026-10-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_readmark'),
    ]

    operations = [
        # The old links may be empty while both exist, so going back can fill them in again (0013).
        migrations.AlterField(
            model_name='motionsession', name='motion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='claimed_sessions', to='conversations.motion'),
        ),
        migrations.AlterField(
            model_name='readmark', name='motion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='read_marks', to='conversations.motion'),
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eth_blockheight', models.BigIntegerField(blank=True, help_text='Block height at which this Mood was opened', null=True)),
            ],
            options={
                'db_table': 'moods',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='conversations.mood'),
        ),
        migrations.AddField(
            model_name='motionsession',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_sessions', to='conversations.mood'),
        ),
        migrations.AddField(
            model_name='readmark',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_marks', to='conversations.mood'),
        ),
        migrations.AddField(
            model_name='setting',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='conversations.mood'),
        ),
        migrations.CreateModel(
            name='MoodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='conversations.mood')),
            ],
            options={
                'db_table': 'mood_aliases',
            },
        ),
    ]
