from django.urls import path
from . import views
from . import views_auth
from . import views_moods
from . import views_runner
from . import views_settings
from . import views_admin

urlpatterns = [
    path('moods/', views_moods.moods_page, name='moods'),
    path('moods/settings/', views_settings.settings_page, name='mood_settings'),
    path('moods/<slug:slug>/rules/', views_settings.rules_page, name='mood_rules'),
    path('moods/manifest.webmanifest', views_moods.app_manifest, name='mood_app_manifest'),
    path('moods/sw.js', views_moods.app_service_worker, name='mood_app_sw'),
    path('moods/icon-<int:size>.png', views_moods.app_icon, name='mood_app_icon'),
    path('moods/<slug:slug>/', views_moods.moods_page, name='mood'),
    path('moods/auth/wiki/', views_auth.wiki_signin, name='mood_wiki_signin'),
    path('moods/auth/wiki/callback', views_auth.wiki_signin_return, name='mood_wiki_return'),
    path('moods/login/<str:code>/', views_auth.login_page, name='mood_login'),
    path('api/auth/challenge/', views_auth.api_challenge, name='auth_challenge'),
    path('api/auth/enroll/', views_auth.api_enroll, name='auth_enroll'),
    path('api/auth/me/', views_auth.api_me, name='auth_me'),
    path('api/auth/logout/', views_auth.api_logout, name='auth_logout'),
    path('api/auth/devices/', views_auth.api_devices, name='auth_devices'),
    path('api/auth/devices/<uuid:device_id>/revoke/', views_auth.api_device_revoke, name='auth_device_revoke'),
    path('api/auth/renew/', views_auth.api_renew, name='auth_renew'),
    path('api/attest/', views_auth.api_attest, name='api_attest'),
    path('api/moods/<slug:slug>/say/', views_auth.api_say, name='api_mood_say'),
    path('api/clips/', views_auth.api_clips, name='api_clips'),
    path('api/moods/<slug:slug>/rename/', views_auth.api_rename, name='api_mood_rename'),
    path('api/moods/', views_moods.api_moods, name='api_moods'),
    path('api/moods/pulse/', views_moods.api_pulse, name='api_moods_pulse'),
    path('api/settings/', views_settings.api_settings, name='api_settings'),
    path('api/auth/admin/', views_admin.api_admin, name='api_auth_admin'),
    path('api/moods/<slug:slug>/turns/', views_moods.api_mood_turns, name='api_mood_turns'),
    path('api/moods/<slug:slug>/sessions/', views_moods.api_mood_sessions, name='api_mood_sessions'),
    path('api/moods/<slug:slug>/steps/<str:step_id>/', views_moods.api_mood_step, name='api_mood_step'),
    path('api/moods/<slug:slug>/typing/', views_moods.api_typing, name='api_mood_typing'),
    path('api/moods/<slug:slug>/interrupt/', views_auth.api_interrupt, name='api_mood_interrupt'),
    path('api/moods/<slug:slug>/archive/', views_auth.api_archive, name='api_mood_archive'),
    path('api/moods/<slug:slug>/pin/', views_auth.api_pin, name='api_mood_pin'),
    path('api/moods/<slug:slug>/memo/', views_auth.api_memo, name='api_mood_memo'),
    path('api/moods/<slug:slug>/speak/<str:message_id>/', views_auth.api_speak, name='api_mood_speak'),
    path('api/moods/<slug:slug>/verify/<str:message_id>/', views_auth.api_verify, name='api_mood_verify'),
    path('api/voice/voices/', views_auth.api_voices, name='api_voices'),
    path('api/voice/speaker/', views_auth.api_speaker_voice, name='api_speaker_voice'),
    path('api/moods/<slug:slug>/media/', views_auth.api_media, name='api_mood_media'),
    path('api/moods/<slug:slug>/stream/', views_runner.api_stream, name='api_mood_stream'),
    path('api/moods/<slug:slug>/quiet/', views_runner.api_quiet, name='api_mood_quiet'),
    path('api/moods/<slug:slug>/held/', views_runner.api_held, name='api_mood_held'),
    path('api/deploys/', views_runner.api_deploys, name='api_deploys'),
    path('api/servers/', views_runner.api_servers, name='api_servers'),
    path('moods/media/<str:sha256>.<str:ext>', views_moods.media_file, name='mood_media'),
    # Where media lived before Moods were Moods: the record's text still links here.
    path('motions/media/<str:sha256>.<str:ext>', views_moods.media_file, name='mood_media_before'),
    path('api/wikilinks/', views_moods.api_wikilinks, name='api_wikilinks'),
    path('api/mentions/<slug:name>/', views_moods.api_mentions, name='api_mentions'),
    path('api/notices/<slug:name>/', views_moods.api_notices, name='api_notices'),
    path('api/moods/new/', views_auth.api_new_mood, name='api_moods_new'),
    path('api/seen/', views_auth.api_seen, name='api_seen'),
    path('api/push/', views_auth.api_push, name='api_push'),
    path('api/push/subscribe/', views_auth.api_push_subscribe, name='api_push_subscribe'),
    path('api/push/unsubscribe/', views_auth.api_push_unsubscribe, name='api_push_unsubscribe'),
    path('api/moods/recent/', views_moods.api_recent, name='api_moods_recent'),
    path('api/moods/live/', views_moods.api_moods_live, name='api_moods_live'),
    path('api/block/', views_moods.api_block, name='api_block'),
    path('api/search/', views_moods.api_search, name='api_search'),
    path('api/work/', views_moods.api_work, name='api_work'),
    path('memory_lane/', views.memory_lane, name='memory_lane'),
    path('spy/', views.stream, name='spy'),
    path('api/recent_messages/', views.recent_messages, name='recent_messages'),
    path('api/messages/', views.api_messages, name='api_messages'),
    path('api/all_messages/', views.all_messages, name='all_messages'),
    path('api/heap_metadata/', views.heap_metadata, name='heap_metadata'),
    path('api/heap_messages/<str:heap_id>/', views.heap_messages, name='heap_messages'),
    path('api/messages_since/<str:message_id>/', views.messages_since, name='messages_since'),
    path('api/ingest/', views.ingest, name='ingest'),
]
